name: time_tracker
description: Example of flutter_login package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  neuss_utils:
    git:
      url: https://github.com/abuzeit/neuss_utils.git
      ref: ^1.0.8
  flutter_login: ^5.0.0
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.2
  stop_watch_timer: ^3.2.1
  shared_preferences: ^2.5.2
  flutter_datetime_picker: ^1.5.1
  flutter_holo_date_picker: ^2.0.0
  dio: ^5.8.0+1
  flutter_launcher_icons:
  flutter_time_picker_spinner: ^2.0.0
  animated_theme_switcher: ^2.0.10
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  mqtt_client: ^10.7.0
  mongo_dart: ^0.10.4
  get: ^4.7.2
#  one_clock: ^2.0.0
flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/icon.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/icon.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"
dependency_overrides:
  #  neuss_utils:
  #    path: E:\Work\Flutter_Projects\neuss_base_app\neuss_base_app

  win32: ^5.11.0
  sensors_plus: ^6.1.1
  http: ^1.3.0
  web: ^1.1.0
  ffi: ^2.1.4
  intl: ^0.20.2
  device_info_plus: ^11.3.0
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.17
  package_info_plus: ^8.2.1
  file_selector_linux: ^0.9.3+2
  uuid: ^4.5.1
  js: ^0.7.2
  flutter_lints: ^5.0.0
  infinite_scroll_pagination: ^4.1.0
  file_picker: ^9.0.0
  share_plus: ^10.1.4

  firebase_core: ^3.12.0
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  form_builder_extra_fields: ^11.1.0
  dropdown_search: ^6.0.2

dev_dependencies:
  #  flutter_test:
  #    sdk: flutter
  lint: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/ecorp.png
    - assets/images/icon.png
    - assets/images/ecorp-lightblue.png
    - assets/images/ecorp-lightgreen.png
    - assets/images/profile.webp

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSansPro-BoldItalic.ttf
          weight: 700
          style: italic
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
